ALTER TABLE DOM_MANUFACTURER MODIFY 	NAME								NVARCHAR2(256)			NOT NULL;
ALTER TABLE DOM_MANUFACTURER DROP CONSTRAINT UNIQUE_MANUFACTURER#NAME;

ALTER TABLE DOM_MANUFACTURER ADD CONSTRAINT UNIQUE_MANUFACTURER#NAME#COUNT UNIQUE (NAME,COUNTRY);

ALTER TABLE DOM_BIKE MODIFY 	DESCRIPTION					CLOB;
ALTER TABLE DOM_BIKE MODIFY 	WEIGHT							NUMBER;
ALTER TABLE DOM_BIKE MODIFY 	PRICE								NUMBER;

ALTER TABLE DOM_BIKE ADD CONSTRAINT UNIQUE_BIKE#MANUFACTURER#MODEL UNIQUE (MANUFACTURER_ID,MODEL);
DROP INDEX DOM_IDX_BIKE#WEIGHT;

DROP TABLE DOM_CITY_BIKE_FEATURES;
ALTER TABLE DOM_CLIENT MODIFY 	DISPOSABLE_MONEY		NUMBER							NOT NULL;
DROP TABLE DOM_GRAVEL_BIKE;

DROP TABLE DOM_GRAVEL_BIKE;

DROP TABLE DOM_GRAVEL_BIKE;

