ALTER TABLE DOM_MANUFACTURER MODIFY COLUMN 	NAME								VARCHAR(256) CHARACTER SET UTF8MB4		NOT NULL;
ALTER TABLE DOM_MANUFACTURER DROP INDEX UNIQUE_MANUFACTURER$NAME;

ALTER TABLE DOM_MANUFACTURER ADD CONSTRAINT UNIQUE_MANUFACTURER$NAME$COUNTRY UNIQUE (NAME,COUNTRY);

ALTER TABLE DOM_BIKE MODIFY COLUMN 	DESCRIPTION					LONGTEXT CHARACTER SET UTF8MB4;
ALTER TABLE DOM_BIKE MODIFY COLUMN 	WEIGHT							DOUBLE;
ALTER TABLE DOM_BIKE MODIFY COLUMN 	PRICE								DOUBLE;

ALTER TABLE DOM_BIKE ADD CONSTRAINT UNIQUE_BIKE$MANUFACTURER$MODEL UNIQUE (MANUFACTURER_ID,MODEL);
DROP INDEX DOM_IDX_BIKE$WEIGHT;

DROP TABLE DOM_CITY_BIKE_FEATURES;
ALTER TABLE DOM_CLIENT MODIFY COLUMN 	DISPOSABLE_MONEY		DOUBLE							NOT NULL;
DROP TABLE DOM_GRAVEL_BIKE;

DROP TABLE DOM_GRAVEL_BIKE;

DROP TABLE DOM_GRAVEL_BIKE;

