CREATE TABLE DOM_MANUFACTURER
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	LAST_MODIFIED				TIMESTAMP,
	COUNTRY							NVARCHAR2(64)
);
CREATE INDEX DOM_IDX_MANUFACTURER#LAST_MODI ON DOM_MANUFACTURER (LAST_MODIFIED);


ALTER TABLE DOM_BIKE MODIFY 	MODEL								NVARCHAR2(64);
ALTER TABLE DOM_BIKE ADD 	DROPPED							NUMBER;
ALTER TABLE DOM_BIKE_SIZES DROP COLUMN ELEMENT_ORDER;
ALTER TABLE DOM_BIKE_SIZES ADD CONSTRAINT UNIQUE_BIKE_SIZES#BIKE#ELEMENT UNIQUE (BIKE_ID,ELEMENT);
ALTER TABLE DOM_BIKE MODIFY 	PRICE								NUMBER;
ALTER TABLE DOM_BIKE ADD 	MANUFACTURER_ID			NUMBER;
ALTER TABLE DOM_BIKE ADD CONSTRAINT FK_BIKE#MANUFACTURER FOREIGN KEY (MANUFACTURER_ID) REFERENCES DOM_MANUFACTURER(ID);

ALTER TABLE DOM_BIKE DROP CONSTRAINT UNIQUE_BIKE#MODEL;
ALTER TABLE DOM_BIKE ADD CONSTRAINT UNIQUE_BIKE#MANUFACTURER#MODEL UNIQUE (MANUFACTURER_ID,MODEL);
CREATE INDEX DOM_IDX_BIKE#WEIGHT ON DOM_BIKE (WEIGHT);

CREATE TABLE DOM_CITY_BIKE_FEATURES
(
	CITY_BIKE_ID				NUMBER							NOT NULL,
	ELEMENT							NVARCHAR2(64),

	CONSTRAINT UNIQUE_CITY_BIKE_FEATURES#CITY UNIQUE (CITY_BIKE_ID,ELEMENT)
);

CREATE TABLE DOM_CLIENT
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	LAST_MODIFIED				TIMESTAMP,
	FIRST_NAME					NVARCHAR2(256)			NOT NULL,
	GENDER							NVARCHAR2(64),
	COUNTRY							NVARCHAR2(64),
	BIKE_SIZE						NVARCHAR2(64),

	CONSTRAINT UNIQUE_CLIENT#FIRST#COUNTRY UNIQUE (FIRST_NAME,COUNTRY)
);
CREATE INDEX DOM_IDX_CLIENT#LAST_MODIFIED ON DOM_CLIENT (LAST_MODIFIED);
CREATE INDEX DOM_IDX_CLIENT#BIKE_SIZE ON DOM_CLIENT (BIKE_SIZE);

CREATE TABLE DOM_CLIENT_WANTED_BIKES_MAX_PR
(
	CLIENT_ID						NUMBER							NOT NULL,
	ENTRY_KEY						NVARCHAR2(256),
	ENTRY_VALUE					NUMBER,

	CONSTRAINT UNIQUE_CLIENT_WANTED_BIKES_MAX UNIQUE (CLIENT_ID,ENTRY_KEY)
);


ALTER TABLE DOM_CITY_BIKE_FEATURES ADD CONSTRAINT FK_CITY_BIKE_FEATURES#CITY_BIK FOREIGN KEY (CITY_BIKE_ID) REFERENCES DOM_CITY_BIKE(ID);
ALTER TABLE DOM_CLIENT_WANTED_BIKES_MAX_PR ADD CONSTRAINT FK_CLIENT_WANTED_BIKES_MAX_PR# FOREIGN KEY (CLIENT_ID) REFERENCES DOM_CLIENT(ID);
