ALTER TABLE DOM_MANUFACTURER ALTER COLUMN 	NAME								NVARCHAR(256)				NOT NULL;
ALTER TABLE DOM_MANUFACTURER DROP CONSTRAINT UNIQUE_MANUFACTURER#NAME;

ALTER TABLE DOM_MANUFACTURER ADD CONSTRAINT UNIQUE_MANUFACTURER#NAME#COUNTRY UNIQUE (NAME,COUNTRY);

ALTER TABLE DOM_BIKE ALTER COLUMN 	DESCRIPTION					NVARCHAR(MAX);
ALTER TABLE DOM_BIKE ALTER COLUMN 	WEIGHT							DOUBLE;
ALTER TABLE DOM_BIKE ALTER COLUMN 	PRICE								DOUBLE;

ALTER TABLE DOM_BIKE ADD CONSTRAINT UNIQUE_BIKE#MANUFACTURER#MODEL UNIQUE (MANUFACTURER_ID,MODEL);
DROP INDEX DOM_IDX_BIKE#WEIGHT;

DROP TABLE DOM_CITY_BIKE_FEATURES;
ALTER TABLE DOM_CLIENT ALTER COLUMN 	DISPOSABLE_MONEY		DOUBLE							NOT NULL;
DROP TABLE DOM_GRAVEL_BIKE;

DROP TABLE DOM_GRAVEL_BIKE;

DROP TABLE DOM_GRAVEL_BIKE;

