ALTER TABLE DOM_A ADD 	L  								NUMBER							NOT NULL;
ALTER TABLE DOM_A MODIFY 	LONG_VALUE					NUMBER;
ALTER TABLE DOM_A ADD 	S  								CLOB;
ALTER TABLE DOM_A ADD CONSTRAINT UNIQUE_A#S UNIQUE (S);
ALTER TABLE DOM_A MODIFY 	DOM_TYPE						NVARCHAR2(64)				NOT NULL;
ALTER TABLE DOM_A DROP COLUMN REMOVED_FIELD;
ALTER TABLE DOM_A DROP CONSTRAINT FK_A#REMOVED_REF_FIELD;
ALTER TABLE DOM_A DROP COLUMN REMOVED_REF_FIELD_ID;
DROP TABLE DOM_A_REMOVED_COLLECTION_FIELD;
CREATE TABLE DOM_A_STRINGS
(
	A_ID								NUMBER							NOT NULL,
	ELEMENT							NVARCHAR2(256),

	CONSTRAINT UNIQUE_A_STRINGS#A#ELEMENT UNIQUE (A_ID,ELEMENT)
);

ALTER TABLE DOM_A_DOUBLE_SET ADD 	ELEMENT_ORDER				NUMBER;
ALTER TABLE DOM_A_DOUBLE_SET DROP CONSTRAINT UNIQUE_A_DOUBLE_SET#A#ELEMENT;
ALTER TABLE DOM_A ADD 	O_ID								NUMBER;
ALTER TABLE DOM_A ADD CONSTRAINT FK_A#O FOREIGN KEY (O_ID) REFERENCES DOM_O(ID) ON DELETE CASCADE;

ALTER TABLE DOM_A DROP CONSTRAINT UNIQUE_A#I;
ALTER TABLE DOM_A ADD CONSTRAINT UNIQUE_A#I#INTEGER UNIQUE (I,INTEGER_VALUE);
CREATE INDEX DOM_IDX_A#L ON DOM_A (L);

CREATE TABLE DOM_Z
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	LAST_MODIFIED				TIMESTAMP,
	X_ID								NUMBER
);
CREATE INDEX DOM_IDX_Z#LAST_MODIFIED ON DOM_Z (LAST_MODIFIED);


ALTER TABLE DOM_A_STRINGS ADD CONSTRAINT FK_A_STRINGS#A FOREIGN KEY (A_ID) REFERENCES DOM_A(ID);
ALTER TABLE DOM_Z ADD CONSTRAINT FK_Z#X FOREIGN KEY (X_ID) REFERENCES DOM_X(ID) ON DELETE CASCADE;
