ALTER TABLE DOM_SEC_B DROP CONSTRAINT FK_SEC_B#AA;
ALTER TABLE DOM_AB DROP CONSTRAINT FK_AB#INHERITANCE;
ALTER TABLE DOM_Z DROP CONSTRAINT FK_Z#X;
ALTER TABLE DOM_X_IS DROP CONSTRAINT FK_X_IS#X;
ALTER TABLE DOM_X DROP CONSTRAINT FK_X#Y;
ALTER TABLE DOM_X DROP CONSTRAINT FK_X#A;
ALTER TABLE DOM_Y DROP CONSTRAINT FK_Y#Z;
ALTER TABLE DOM_Y DROP CONSTRAINT FK_Y#Y;
ALTER TABLE DOM_AA DROP CONSTRAINT FK_AA#INHERITANCE;
ALTER TABLE DOM_A_MAP_OF_MAPS DROP CONSTRAINT FK_A_MAP_OF_MAPS#A;
ALTER TABLE DOM_A_MAP_OF_LISTS DROP CONSTRAINT FK_A_MAP_OF_LISTS#A;
ALTER TABLE DOM_A_LIST_OF_MAPS DROP CONSTRAINT FK_A_LIST_OF_MAPS#A;
ALTER TABLE DOM_A_LIST_OF_LISTS DROP CONSTRAINT FK_A_LIST_OF_LISTS#A;
ALTER TABLE DOM_A_BIG_DECIMAL_MAP DROP CONSTRAINT FK_A_BIG_DECIMAL_MAP#A;
ALTER TABLE DOM_A_DOUBLE_SET DROP CONSTRAINT FK_A_DOUBLE_SET#A;
ALTER TABLE DOM_A_STRINGS DROP CONSTRAINT FK_A_STRINGS#A;
ALTER TABLE DOM_A_STRING_ARRAY DROP CONSTRAINT FK_A_STRING_ARRAY#A;
ALTER TABLE DOM_A DROP CONSTRAINT FK_A#O;
ALTER TABLE DOM_A_INNER DROP CONSTRAINT FK_A_INNER#A;
ALTER TABLE DOM_C DROP CONSTRAINT FK_C#C;

DROP TABLE DOM_SEC_B;
DROP TABLE DOM_AB;
DROP TABLE DOM_Z;
DROP TABLE DOM_X_IS;
DROP TABLE DOM_X;
DROP TABLE DOM_X_IN_PROGRESS;
DROP TABLE DOM_Y;
DROP TABLE DOM_AA;
DROP TABLE DOM_A_MAP_OF_MAPS;
DROP TABLE DOM_A_MAP_OF_LISTS;
DROP TABLE DOM_A_LIST_OF_MAPS;
DROP TABLE DOM_A_LIST_OF_LISTS;
DROP TABLE DOM_A_BIG_DECIMAL_MAP;
DROP TABLE DOM_A_DOUBLE_SET;
DROP TABLE DOM_A_STRINGS;
DROP TABLE DOM_A_STRING_ARRAY;
DROP TABLE DOM_A;
DROP TABLE DOM_A_INNER;
DROP TABLE DOM_O;
DROP TABLE DOM_C;

CREATE TABLE DOM_C
(
	DOMAIN_CLASS				NVARCHAR(64),
	ID 								BIGINT							PRIMARY KEY,
	LAST_MODIFIED				DATETIME,
	NAME								NVARCHAR(512),
	C_ID								BIGINT
);
CREATE INDEX DOM_IDX_C#LAST_MODIFIED ON DOM_C (LAST_MODIFIED);

CREATE TABLE DOM_O
(
	DOMAIN_CLASS				NVARCHAR(64),
	ID 								BIGINT							PRIMARY KEY,
	LAST_MODIFIED				DATETIME
);
CREATE INDEX DOM_IDX_O#LAST_MODIFIED ON DOM_O (LAST_MODIFIED);

CREATE TABLE DOM_A_INNER
(
	DOMAIN_CLASS				NVARCHAR(64),
	ID 								BIGINT							PRIMARY KEY,
	LAST_MODIFIED				DATETIME,
	A_ID								BIGINT
);
CREATE INDEX DOM_IDX_A_INNER#LAST_MODIFIED ON DOM_A_INNER (LAST_MODIFIED);

CREATE TABLE DOM_A
(
	DOMAIN_CLASS				NVARCHAR(64),
	ID 								BIGINT							PRIMARY KEY,
	LAST_MODIFIED				DATETIME,
	BOOLEAN							NVARCHAR(5)					NOT NULL,
	BOOLEAN_VALUE				NVARCHAR(5),
	SH 								SMALLINT						NOT NULL,
	SHORT_VALUE					SMALLINT,
	I  								INTEGER							NOT NULL,
	INTEGER_VALUE				INTEGER,
	L  								BIGINT							NOT NULL,
	LONG_VALUE					BIGINT,
	D  								FLOAT								NOT NULL,
	DOUBLE_VALUE				FLOAT,
	C  								NVARCHAR(1)					NOT NULL,
	CHAR_VALUE					NVARCHAR(1),
	BIG_INTEGER_VALUE		BIGINT,
	BIG_DECIMAL_VALUE		FLOAT,
	DATETIME						DATETIME,
	DOM_DATE						DATE,
	TIME								TIME,
	S  								NVARCHAR(16),
	STRUCTURE						NVARCHAR(512),
	PICTURE							VARBINARY(MAX),
	DOM_LONGTEXT				NVARCHAR(MAX),
	DOM_FILE						VARBINARY(MAX),
	DOM_TYPE						NVARCHAR(64)				NOT NULL,
	SEC_SECRET_STRING		NVARCHAR(512),
	PWD 								NVARCHAR(512),
	DEPRECATED_FIELD		NVARCHAR(512),
	O_ID								BIGINT,

	CONSTRAINT UNIQUE_A#S UNIQUE (S),

	CONSTRAINT UNIQUE_A#I#INTEGER UNIQUE (I,INTEGER_VALUE)
);
CREATE INDEX DOM_IDX_A#LAST_MODIFIED ON DOM_A (LAST_MODIFIED);
CREATE INDEX DOM_IDX_A#L ON DOM_A (L);
CREATE INDEX DOM_IDX_A#LONG_VALUE ON DOM_A (LONG_VALUE);

CREATE TABLE DOM_A_STRING_ARRAY
(
	A_ID								BIGINT							NOT NULL,
	ELEMENT							NVARCHAR(512),
	ELEMENT_ORDER				BIGINT
);

CREATE TABLE DOM_A_STRINGS
(
	A_ID								BIGINT							NOT NULL,
	ELEMENT							NVARCHAR(512),
	ELEMENT_ORDER				BIGINT,

	CONSTRAINT UNIQUE_A_STRINGS#A#ELEMENT UNIQUE (A_ID,ELEMENT_ORDER)
);

CREATE TABLE DOM_A_DOUBLE_SET
(
	A_ID								BIGINT							NOT NULL,
	ELEMENT							FLOAT,

	CONSTRAINT UNIQUE_A_DOUBLE_SET#A#ELEMENT UNIQUE (A_ID,ELEMENT)
);

CREATE TABLE DOM_A_BIG_DECIMAL_MAP
(
	A_ID								BIGINT							NOT NULL,
	ENTRY_KEY						NVARCHAR(512),
	ENTRY_VALUE					FLOAT,

	CONSTRAINT UNIQUE_A_BIG_DECIMAL_MAP#A#ENTRY UNIQUE (A_ID,ENTRY_KEY)
);

CREATE TABLE DOM_A_LIST_OF_LISTS
(
	A_ID								BIGINT							NOT NULL,
	ELEMENT							NVARCHAR(MAX),
	ELEMENT_ORDER				BIGINT,

	CONSTRAINT UNIQUE_A_LIST_OF_LISTS#A#ELEMENT UNIQUE (A_ID,ELEMENT_ORDER)
);

CREATE TABLE DOM_A_LIST_OF_MAPS
(
	A_ID								BIGINT							NOT NULL,
	ELEMENT							NVARCHAR(MAX),
	ELEMENT_ORDER				BIGINT,

	CONSTRAINT UNIQUE_A_LIST_OF_MAPS#A#ELEMENT UNIQUE (A_ID,ELEMENT_ORDER)
);

CREATE TABLE DOM_A_MAP_OF_LISTS
(
	A_ID								BIGINT							NOT NULL,
	ENTRY_KEY						BIGINT,
	ENTRY_VALUE					NVARCHAR(MAX),

	CONSTRAINT UNIQUE_A_MAP_OF_LISTS#A#ENTRY UNIQUE (A_ID,ENTRY_KEY)
);

CREATE TABLE DOM_A_MAP_OF_MAPS
(
	A_ID								BIGINT							NOT NULL,
	ENTRY_KEY						NVARCHAR(512),
	ENTRY_VALUE					NVARCHAR(MAX),

	CONSTRAINT UNIQUE_A_MAP_OF_MAPS#A#ENTRY UNIQUE (A_ID,ENTRY_KEY)
);

CREATE TABLE DOM_AA
(
	DOMAIN_CLASS				NVARCHAR(64),
	ID 								BIGINT							PRIMARY KEY
);

CREATE TABLE DOM_Y
(
	DOMAIN_CLASS				NVARCHAR(64),
	ID 								BIGINT							PRIMARY KEY,
	LAST_MODIFIED				DATETIME,
	Y_ID								BIGINT,
	Z_ID								BIGINT							NOT NULL
);
CREATE INDEX DOM_IDX_Y#LAST_MODIFIED ON DOM_Y (LAST_MODIFIED);

CREATE TABLE DOM_X_IN_PROGRESS
(
	DOMAIN_CLASS				NVARCHAR(64),
	ID 								BIGINT							PRIMARY KEY,
	LAST_MODIFIED				DATETIME
);
CREATE INDEX DOM_IDX_X_IN_PROGRESS#LAST_MODIFIED ON DOM_X_IN_PROGRESS (LAST_MODIFIED);

CREATE TABLE DOM_X
(
	DOMAIN_CLASS				NVARCHAR(64),
	ID 								BIGINT							PRIMARY KEY,
	LAST_MODIFIED				DATETIME,
	S  								NVARCHAR(512),
	A_ID								BIGINT,
	Y_ID								BIGINT
);
CREATE INDEX DOM_IDX_X#LAST_MODIFIED ON DOM_X (LAST_MODIFIED);

CREATE TABLE DOM_X_IS
(
	X_ID								BIGINT							NOT NULL,
	ELEMENT							INTEGER,
	ELEMENT_ORDER				BIGINT,

	CONSTRAINT UNIQUE_X_IS#X#ELEMENT UNIQUE (X_ID,ELEMENT_ORDER)
);

CREATE TABLE DOM_Z
(
	DOMAIN_CLASS				NVARCHAR(64),
	ID 								BIGINT							PRIMARY KEY,
	LAST_MODIFIED				DATETIME,
	X_ID								BIGINT
);
CREATE INDEX DOM_IDX_Z#LAST_MODIFIED ON DOM_Z (LAST_MODIFIED);

CREATE TABLE DOM_AB
(
	DOMAIN_CLASS				NVARCHAR(64),
	ID 								BIGINT							PRIMARY KEY
);

CREATE TABLE DOM_SEC_B
(
	DOMAIN_CLASS				NVARCHAR(64),
	ID 								BIGINT							PRIMARY KEY,
	LAST_MODIFIED				DATETIME,
	NAME								NVARCHAR(512),
	AA_ID								BIGINT
);
CREATE INDEX DOM_IDX_SEC_B#LAST_MODIFIED ON DOM_SEC_B (LAST_MODIFIED);


ALTER TABLE DOM_C ADD CONSTRAINT FK_C#C FOREIGN KEY (C_ID) REFERENCES DOM_C(ID);
ALTER TABLE DOM_A_INNER ADD CONSTRAINT FK_A_INNER#A FOREIGN KEY (A_ID) REFERENCES DOM_A(ID);
ALTER TABLE DOM_A ADD CONSTRAINT FK_A#O FOREIGN KEY (O_ID) REFERENCES DOM_O(ID) ON DELETE CASCADE;
ALTER TABLE DOM_A_STRING_ARRAY ADD CONSTRAINT FK_A_STRING_ARRAY#A FOREIGN KEY (A_ID) REFERENCES DOM_A(ID);
ALTER TABLE DOM_A_STRINGS ADD CONSTRAINT FK_A_STRINGS#A FOREIGN KEY (A_ID) REFERENCES DOM_A(ID);
ALTER TABLE DOM_A_DOUBLE_SET ADD CONSTRAINT FK_A_DOUBLE_SET#A FOREIGN KEY (A_ID) REFERENCES DOM_A(ID);
ALTER TABLE DOM_A_BIG_DECIMAL_MAP ADD CONSTRAINT FK_A_BIG_DECIMAL_MAP#A FOREIGN KEY (A_ID) REFERENCES DOM_A(ID);
ALTER TABLE DOM_A_LIST_OF_LISTS ADD CONSTRAINT FK_A_LIST_OF_LISTS#A FOREIGN KEY (A_ID) REFERENCES DOM_A(ID);
ALTER TABLE DOM_A_LIST_OF_MAPS ADD CONSTRAINT FK_A_LIST_OF_MAPS#A FOREIGN KEY (A_ID) REFERENCES DOM_A(ID);
ALTER TABLE DOM_A_MAP_OF_LISTS ADD CONSTRAINT FK_A_MAP_OF_LISTS#A FOREIGN KEY (A_ID) REFERENCES DOM_A(ID);
ALTER TABLE DOM_A_MAP_OF_MAPS ADD CONSTRAINT FK_A_MAP_OF_MAPS#A FOREIGN KEY (A_ID) REFERENCES DOM_A(ID);
ALTER TABLE DOM_AA ADD CONSTRAINT FK_AA#INHERITANCE FOREIGN KEY (ID) REFERENCES DOM_A(ID) ON DELETE CASCADE;
ALTER TABLE DOM_Y ADD CONSTRAINT FK_Y#Y FOREIGN KEY (Y_ID) REFERENCES DOM_Y(ID);
ALTER TABLE DOM_Y ADD CONSTRAINT FK_Y#Z FOREIGN KEY (Z_ID) REFERENCES DOM_Z(ID);
ALTER TABLE DOM_X ADD CONSTRAINT FK_X#A FOREIGN KEY (A_ID) REFERENCES DOM_A(ID) ON DELETE CASCADE;
ALTER TABLE DOM_X ADD CONSTRAINT FK_X#Y FOREIGN KEY (Y_ID) REFERENCES DOM_Y(ID);
ALTER TABLE DOM_X_IS ADD CONSTRAINT FK_X_IS#X FOREIGN KEY (X_ID) REFERENCES DOM_X(ID);
ALTER TABLE DOM_Z ADD CONSTRAINT FK_Z#X FOREIGN KEY (X_ID) REFERENCES DOM_X(ID);
ALTER TABLE DOM_AB ADD CONSTRAINT FK_AB#INHERITANCE FOREIGN KEY (ID) REFERENCES DOM_A(ID) ON DELETE CASCADE;
ALTER TABLE DOM_SEC_B ADD CONSTRAINT FK_SEC_B#AA FOREIGN KEY (AA_ID) REFERENCES DOM_AA(ID);
