ALTER TABLE DOM_MTB DROP CONSTRAINT FK_MTB#INHERITANCE;
ALTER TABLE DOM_CITY_BIKE_FEATURES DROP CONSTRAINT FK_CITY_BIKE_FEATURES#CITY_BIK;
ALTER TABLE DOM_CITY_BIKE DROP CONSTRAINT FK_CITY_BIKE#INHERITANCE;
ALTER TABLE DOM_ORDER DROP CONSTRAINT FK_ORDER#BIKE;
ALTER TABLE DOM_ORDER DROP CONSTRAINT FK_ORDER#CLIENT;
ALTER TABLE DOM_CLIENT_WANTED_BIKES_MAX_PR DROP CONSTRAINT FK_CLIENT_WANTED_BIKES_MAX_PR#;
ALTER TABLE DOM_RACE_BIKE_AVAILABLE_GROUP_ DROP CONSTRAINT FK_RACE_BIKE_AVAILABLE_GROUP_#;
ALTER TABLE DOM_RACE_BIKE DROP CONSTRAINT FK_RACE_BIKE#INHERITANCE;
ALTER TABLE DOM_BIKE_AVAILABILITY_MAP DROP CONSTRAINT FK_BIKE_AVAILABILITY_MAP#BIKE;
ALTER TABLE DOM_BIKE_SIZES DROP CONSTRAINT FK_BIKE_SIZES#BIKE;
ALTER TABLE DOM_BIKE DROP CONSTRAINT FK_BIKE#MANUFACTURER;

DROP TABLE DOM_MTB;
DROP TABLE DOM_CITY_BIKE_FEATURES;
DROP TABLE DOM_CITY_BIKE;
DROP TABLE DOM_ORDER;
DROP TABLE DOM_ORDER_IN_PROGRESS;
DROP TABLE DOM_CLIENT_WANTED_BIKES_MAX_PR;
DROP TABLE DOM_CLIENT;
DROP TABLE DOM_CLIENT_REGION_IN_PROGRESS;
DROP TABLE DOM_RACE_BIKE_AVAILABLE_GROUP_;
DROP TABLE DOM_RACE_BIKE;
DROP TABLE DOM_BIKE_AVAILABILITY_MAP;
DROP TABLE DOM_BIKE_SIZES;
DROP TABLE DOM_BIKE;
DROP TABLE DOM_BIKE_IN_PROGRESS;
DROP TABLE DOM_MANUFACTURER;

CREATE TABLE DOM_MANUFACTURER
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	LAST_MODIFIED				TIMESTAMP,
	NAME								NVARCHAR2(256)			NOT NULL,
	COUNTRY							NVARCHAR2(64),

	CONSTRAINT UNIQUE_MANUFACTURER#NAME UNIQUE (NAME)
);
CREATE INDEX DOM_IDX_MANUFACTURER#LAST_MODI ON DOM_MANUFACTURER (LAST_MODIFIED);

CREATE TABLE DOM_BIKE_IN_PROGRESS
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	LAST_MODIFIED				TIMESTAMP
);
CREATE INDEX DOM_IDX_BIKE_IN_PROGRESS#LAST_ ON DOM_BIKE_IN_PROGRESS (LAST_MODIFIED);

CREATE TABLE DOM_BIKE
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	LAST_MODIFIED				TIMESTAMP,
	MODEL								NVARCHAR2(64)				NOT NULL,
	DESCRIPTION					CLOB,
	FRAME								NVARCHAR2(64),
	BREAKS							NVARCHAR2(64),
	GEARS								NUMBER							NOT NULL,
	WEIGHT							NUMBER,
	IS_FOR_WOMAN				NVARCHAR2(5)				NOT NULL,
	PRICE								NUMBER							NOT NULL,
	PICTURE							BLOB,
	MANUFACTURER_ID			NUMBER							NOT NULL,

	CONSTRAINT UNIQUE_BIKE#MANUFACTURER#MODEL UNIQUE (MANUFACTURER_ID,MODEL)
);
CREATE INDEX DOM_IDX_BIKE#LAST_MODIFIED ON DOM_BIKE (LAST_MODIFIED);

CREATE TABLE DOM_BIKE_SIZES
(
	BIKE_ID							NUMBER							NOT NULL,
	ELEMENT							NVARCHAR2(64),
	ELEMENT_ORDER				NUMBER
);

CREATE TABLE DOM_BIKE_AVAILABILITY_MAP
(
	BIKE_ID							NUMBER							NOT NULL,
	ENTRY_KEY						NVARCHAR2(64),
	ENTRY_VALUE					NUMBER,

	CONSTRAINT UNIQUE_BIKE_AVAILABILITY_MAP#B UNIQUE (BIKE_ID,ENTRY_KEY)
);

CREATE TABLE DOM_RACE_BIKE
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	IS_AERO							NVARCHAR2(5)				NOT NULL,
	IS_FRAME_ONLY				NVARCHAR2(5)				NOT NULL,
	IS_GEAR_SHIFT_ELECTRIC		NVARCHAR2(5)				NOT NULL,
	RIM 								NVARCHAR2(64)
);

CREATE TABLE DOM_RACE_BIKE_AVAILABLE_GROUP_
(
	RACE_BIKE_ID				NUMBER							NOT NULL,
	ELEMENT							NVARCHAR2(64),

	CONSTRAINT UNIQUE_RACE_BIKE_AVAILABLE_GRO UNIQUE (RACE_BIKE_ID,ELEMENT)
);

CREATE TABLE DOM_CLIENT_REGION_IN_PROGRESS
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	LAST_MODIFIED				TIMESTAMP,
	REGION							NVARCHAR2(64),

	CONSTRAINT UNIQUE_CLIENT_REGION_IN_PROGRE UNIQUE (REGION)
);
CREATE INDEX DOM_IDX_CLIENT_REGION_IN_PROGR ON DOM_CLIENT_REGION_IN_PROGRESS (LAST_MODIFIED);

CREATE TABLE DOM_CLIENT
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	LAST_MODIFIED				TIMESTAMP,
	FIRST_NAME					NVARCHAR2(256)			NOT NULL,
	GENDER							NVARCHAR2(64),
	COUNTRY							NVARCHAR2(64),
	BIKE_SIZE						NVARCHAR2(64),
	DISPOSABLE_MONEY		NUMBER							NOT NULL,

	CONSTRAINT UNIQUE_CLIENT#FIRST#COUNTRY UNIQUE (FIRST_NAME,COUNTRY)
);
CREATE INDEX DOM_IDX_CLIENT#LAST_MODIFIED ON DOM_CLIENT (LAST_MODIFIED);
CREATE INDEX DOM_IDX_CLIENT#BIKE_SIZE ON DOM_CLIENT (BIKE_SIZE);

CREATE TABLE DOM_CLIENT_WANTED_BIKES_MAX_PR
(
	CLIENT_ID						NUMBER							NOT NULL,
	ENTRY_KEY						NVARCHAR2(256),
	ENTRY_VALUE					NUMBER,

	CONSTRAINT UNIQUE_CLIENT_WANTED_BIKES_MAX UNIQUE (CLIENT_ID,ENTRY_KEY)
);

CREATE TABLE DOM_ORDER_IN_PROGRESS
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	LAST_MODIFIED				TIMESTAMP
);
CREATE INDEX DOM_IDX_ORDER_IN_PROGRESS#LAST ON DOM_ORDER_IN_PROGRESS (LAST_MODIFIED);

CREATE TABLE DOM_ORDER
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	LAST_MODIFIED				TIMESTAMP,
	WAS_CANCELED				NVARCHAR2(5)				NOT NULL,
	ORDER_DATE					TIMESTAMP,
	INVOICE_DATE				TIMESTAMP,
	PAY_DATE						TIMESTAMP,
	DELIVERY_DATE				TIMESTAMP,
	CLIENT_ID						NUMBER							NOT NULL,
	BIKE_ID							NUMBER							NOT NULL
);
CREATE INDEX DOM_IDX_ORDER#LAST_MODIFIED ON DOM_ORDER (LAST_MODIFIED);

CREATE TABLE DOM_CITY_BIKE
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY
);

CREATE TABLE DOM_CITY_BIKE_FEATURES
(
	CITY_BIKE_ID				NUMBER							NOT NULL,
	ELEMENT							NVARCHAR2(64),

	CONSTRAINT UNIQUE_CITY_BIKE_FEATURES#CITY UNIQUE (CITY_BIKE_ID,ELEMENT)
);

CREATE TABLE DOM_MTB
(
	DOMAIN_CLASS				NVARCHAR2(64),
	ID 								NUMBER							PRIMARY KEY,
	BIKE_TYPE						NVARCHAR2(64),
	SUSPENSION					NVARCHAR2(64),
	WHEEL_SIZE					NVARCHAR2(64)
);


ALTER TABLE DOM_BIKE ADD CONSTRAINT FK_BIKE#MANUFACTURER FOREIGN KEY (MANUFACTURER_ID) REFERENCES DOM_MANUFACTURER(ID);
ALTER TABLE DOM_BIKE_SIZES ADD CONSTRAINT FK_BIKE_SIZES#BIKE FOREIGN KEY (BIKE_ID) REFERENCES DOM_BIKE(ID);
ALTER TABLE DOM_BIKE_AVAILABILITY_MAP ADD CONSTRAINT FK_BIKE_AVAILABILITY_MAP#BIKE FOREIGN KEY (BIKE_ID) REFERENCES DOM_BIKE(ID);
ALTER TABLE DOM_RACE_BIKE ADD CONSTRAINT FK_RACE_BIKE#INHERITANCE FOREIGN KEY (ID) REFERENCES DOM_BIKE(ID) ON DELETE CASCADE;
ALTER TABLE DOM_RACE_BIKE_AVAILABLE_GROUP_ ADD CONSTRAINT FK_RACE_BIKE_AVAILABLE_GROUP_# FOREIGN KEY (RACE_BIKE_ID) REFERENCES DOM_RACE_BIKE(ID);
ALTER TABLE DOM_CLIENT_WANTED_BIKES_MAX_PR ADD CONSTRAINT FK_CLIENT_WANTED_BIKES_MAX_PR# FOREIGN KEY (CLIENT_ID) REFERENCES DOM_CLIENT(ID);
ALTER TABLE DOM_ORDER ADD CONSTRAINT FK_ORDER#CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES DOM_CLIENT(ID) ON DELETE CASCADE;
ALTER TABLE DOM_ORDER ADD CONSTRAINT FK_ORDER#BIKE FOREIGN KEY (BIKE_ID) REFERENCES DOM_BIKE(ID) ON DELETE CASCADE;
ALTER TABLE DOM_CITY_BIKE ADD CONSTRAINT FK_CITY_BIKE#INHERITANCE FOREIGN KEY (ID) REFERENCES DOM_BIKE(ID) ON DELETE CASCADE;
ALTER TABLE DOM_CITY_BIKE_FEATURES ADD CONSTRAINT FK_CITY_BIKE_FEATURES#CITY_BIK FOREIGN KEY (CITY_BIKE_ID) REFERENCES DOM_CITY_BIKE(ID);
ALTER TABLE DOM_MTB ADD CONSTRAINT FK_MTB#INHERITANCE FOREIGN KEY (ID) REFERENCES DOM_BIKE(ID) ON DELETE CASCADE;
